version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: hel_city_bike
      MYSQL_USER: admin
      MYSQL_PASSWORD: asennus

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: hel_city_bike
      MYSQL_USER: admin
      MYSQL_PASSWORD: asennus
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
